# Generated by Django 4.1.7 on 2023-03-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Tailoring', 'Tailoring'), ('Hair Dressing', 'Hair Dressing'), ('Catering', 'Catering'), ('Plumbing', 'Plumbing'), ('Welding', 'Welding'), ('Electrical Engineering', 'Electrical Engineering'), ('Computer Literacy', 'Computer Literacy'), ('Agriculture', 'Agriculture'), ('Building', 'Building'), ('Carpentry', 'Carpentry')], default='Tailoring', max_length=25),
        ),
    ]
